<script setup>
import { inject, ref, computed, onMounted } from 'vue'
import { api } from '../api'

const props = defineProps({ id: { type: String, required: true } })
const song = inject('song')
const md = ref('')
const err = ref('')

onMounted(async () => {
  md.value = song.value?.chart || ''
  if (!md.value) {
    try { md.value = (await api.chart(props.id)).markdown } catch (e) { err.value = e.message }
  }
})

/**
 * A deliberately small markdown pass: the chart is generated by `chart.py`,
 * so the shapes it can contain are known - headings, fenced tab blocks,
 * bullets and paragraphs. Pulling in a full markdown library to render five
 * constructs would be more surface than the page needs.
 */
const blocks = computed(() => {
  const out = []
  let fence = null
  for (const raw of (md.value || '').split('\n')) {
    if (raw.startsWith('```')) {
      if (fence) { out.push({ t: 'code', text: fence.join('\n') }); fence = null }
      else fence = []
      continue
    }
    if (fence) { fence.push(raw); continue }
    const h = raw.match(/^(#{1,4})\s+(.*)$/)
    if (h) { out.push({ t: `h${h[1].length}`, text: h[2] }); continue }
    if (/^[-*]\s+/.test(raw)) { out.push({ t: 'li', text: raw.replace(/^[-*]\s+/, '') }); continue }
    if (raw.trim()) out.push({ t: 'p', text: raw })
    else out.push({ t: 'gap' })
  }
  if (fence) out.push({ t: 'code', text: fence.join('\n') })
  return out
})

/** `**bold**` and `` `code` `` are the only inline forms chart.py emits. */
function inline(s) {
  return s
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')
    .replace(/`(.+?)`/g, '<code>$1</code>')
}

function download() {
  const blob = new Blob([md.value], { type: 'text/markdown' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `${props.id}-chart.md`
  a.click()
  URL.revokeObjectURL(a.href)
}
</script>

<template>
  <div class="cv">
    <div class="acts">
      <button class="btn btn-sm" @click="download">Download chart.md</button>
      <button class="btn btn-sm btn-ghost" @click="navigator.clipboard.writeText(md)">Copy</button>
    </div>

    <article v-if="md" class="card sheet">
      <template v-for="(b, i) in blocks" :key="i">
        <h1 v-if="b.t === 'h1'" class="h1">{{ b.text }}</h1>
        <h2 v-else-if="b.t === 'h2'" class="h2">{{ b.text }}</h2>
        <h3 v-else-if="b.t === 'h3'" class="h3">{{ b.text }}</h3>
        <h4 v-else-if="b.t === 'h4'" class="h4">{{ b.text }}</h4>
        <pre v-else-if="b.t === 'code'" class="code mono">{{ b.text }}</pre>
        <li v-else-if="b.t === 'li'" class="li" v-html="inline(b.text)" />
        <p v-else-if="b.t === 'p'" class="p" v-html="inline(b.text)" />
        <div v-else class="gap" />
      </template>
    </article>

    <div v-else class="card pad muted">{{ err || 'No chart yet.' }}</div>
  </div>
</template>

<style scoped>
.cv { max-width: 940px; }
.acts { display: flex; gap: 7px; margin-bottom: 12px; }
.sheet { padding: 26px 32px; }

.h1 { font-family: var(--font-display); font-size: 26px; margin-bottom: 10px; }
.h2 {
  font-family: var(--font-display); font-size: 19px; color: var(--red-glow);
  margin: 22px 0 8px; padding-bottom: 5px; border-bottom: 1px solid var(--line-soft);
}
.h3 { font-family: var(--font-display); font-size: 16px; color: var(--gold); margin: 16px 0 6px; }
.h4 { font-size: 13.5px; color: var(--text-2); margin: 12px 0 4px; }
.p { font-size: 14px; color: var(--text-2); margin: 0 0 7px; }
.li { font-size: 14px; color: var(--text-2); margin-left: 20px; }
.gap { height: 5px; }

.code {
  background: var(--bg-deep);
  border: 1px solid var(--line-soft);
  border-radius: var(--r-sm);
  padding: 12px 14px;
  font-size: 11.5px;
  line-height: 1.5;
  color: var(--text-2);
  overflow-x: auto;
  margin: 8px 0 14px;
}
:deep(code) {
  background: var(--surface-2); padding: 1px 5px;
  border-radius: 3px; font-family: var(--font-mono);
  font-size: 12px; color: var(--gold);
}
:deep(b) { color: var(--text); }
.pad { padding: 24px; }
</style>
